export const EIQuestions = [
  "I prefer to spend my free time alone, rather than with other people",
  "I enjoy meeting new people and making new friends",
  "I prefer to work in a group or team rather than alone",
  "I feel energized when I'm around people and interacting with them",
  "I often initiate conversations with others",
  "I prefer to attend social events and parties over staying at home and relaxing",
  "I enjoy being the center of attention and speaking in front of groups of people",
  "I am comfortable in social situations and can talk easily with people I don't know",
  "I like to spend time thinking about my feelings and reflecting on my experiences",
  "I often feel drained after spending time with a large group of people and need time to recharge.",
];
export const questions = [
  {
    id: "ei1",
    text: "I prefer to spend my free time alone, rather than with other people",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei2",
    extrovert: true,
    text: "I enjoy meeting new people and making new friends",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei3",
    extrovert: true,
    text: "I prefer to work in a group or team rather than alone",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei4",
    text: "I feel energized when I'm around people and interacting with them",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei5",
    text: "I often initiate conversations with others",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei6",
    text: "I prefer to attend social events and parties over staying at home and relaxing",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei7",
    text: "I enjoy being the center of attention and speaking in front of groups of people",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei8",
    text: "I am comfortable in social situations and can talk easily with people I don't know",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei9",
    text: "I like to spend time thinking about my feelings and reflecting on my experiences",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "ei10",
    text: "I often feel drained after spending time with a large group of people and need time to recharge",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
];

export const SNquestions = [
  {
    id: "sn1",
    text: "I strongly prefer focusing on concrete details and facts rather than abstract theories and ideas",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn2",
    extrovert: true,
    text: "I generally prefer to work with practical, tangible things rather than theoretical or abstract concepts",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn3",
    extrovert: true,
    text: "I often rely on my five senses to understand and navigate the world around me.",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn4",
    text: "I prefer to learn by doing and experiencing things firsthand, rather than by reading or studying",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn5",
    text: "I tend to be highly observant and detail-oriented in my everyday life",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn6",
    text: `I often rely on my intuition or "gut feeling" to make decisions, rather than relying on logical analysis or reasoning`,
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn7",
    text: "I enjoy exploring abstract concepts and theories, even if they may not have immediate practical application",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn8",
    text: "I frequently find myself daydreaming or getting lost in my thoughts.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn9",
    text: "I prefer to learn by analyzing patterns and connections between ideas, rather than by experiencing things firsthand",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "sn10",
    text: "I enjoy coming up with new and innovative ideas or approaches to problems, even if they may not be conventional or established methods.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
];

export const TFQuestions = [
  {
    id: "tf1",
    text: "When making a decision, I am more likely to consider objective criteria, such as facts and data, rather than my own personal feelings or values",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf2",
    extrovert: true,
    text: "I believe that truth and honesty are important in all circumstances, even if it may hurt someone's feelings or cause conflict",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf3",
    extrovert: true,
    text: "I tend to analyze situations logically and dispassionately, rather than getting caught up in emotions or interpersonal dynamics",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf4",
    text: "I often find it difficult to sympathize with people who make decisions based solely on their emotions, without considering the facts or consequences",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf5",
    text: "When giving feedback, I tend to focus more on areas for improvement than on positive aspects of someone's work or personality.",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf6",
    text: `When making a decision, I am more likely to consider my own personal feelings and values, even if they conflict with objective criteria or data.`,
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf7",
    text: "I believe that it is important to be tactful and considerate of other people's feelings, even if it means compromising on the truth or being less than fully honest.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf8",
    text: "I tend to rely on my intuition and emotional intelligence to understand and navigate interpersonal dynamics, rather than relying solely on logical analysis.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf9",
    text: "I often find it difficult to understand or connect with people who prioritize logic and reason over emotions and relationships.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "tf10",
    text: "When giving feedback, I tend to focus more on building up people's strengths and highlighting positive aspects of their work or personality, rather than dwelling on areas for improvement.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
];

export const JPQuestions = [
  {
    id: "jp1",
    text: "I prefer to work within established systems and structures, rather than taking risks or trying new approaches",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp2",
    extrovert: true,
    text: "I feel most comfortable when I have a clear, predetermined plan for achieving my goals",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp3",
    extrovert: true,
    text: "I often find myself judging others based on how well they conform to established norms and expectations",
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp4",
    text: "I tend to see the world in black and white terms, with little room for shades of gray or ambiguity.",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp5",
    text: "I feel uneasy when circumstances change unexpectedly, and prefer to have a plan in place to adapt to these changes.",
    extrovert: true,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp6",
    text: `I enjoy exploring new ideas and approaches, even if they do not align with established norms or expectations`,
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp7",
    text: "I am comfortable adapting to changing circumstances and improvising as needed, rather than sticking to a predetermined plan",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp8",
    text: "I often find myself appreciating and seeking out new experiences and perspectives, even if they differ from my own personal values or beliefs.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp9",
    text: "I tend to see the world in nuanced terms, with a willingness to consider multiple perspectives and shades of gray.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
  {
    id: "jp10",
    text: "I enjoy the spontaneity and unpredictability of life, and feel energized by sudden changes or unexpected opportunities.",
    extrovert: false,
    options: [
      { value: "2", label: "Strong agree" },
      { value: "1", label: "Weak agree" },
      { value: "0", label: "I Dont know" },
      { value: "-1", label: "Weak Disagree" },
      { value: "-2", label: "Strong Disagree" },
    ],
  },
];
